function [F_AB_x, F_AB_y] = gravity_force(m_A, m_B, x_A, x_B, y_A, y_B)
%Author:    Lukas Rohrmueller
%Date:      January 22nd, 2020
%About:     Calculation of the Force acting on Body B generated by Body A

%Inputs:    m_A:    Mass of Body A in kg
%           m_B:    Mass of Body B in kg
%           x_A:    X-Position of Point A in m
%           x_B:    X-Position of Point B in m
%           y_A:    Y-Position of Point A in m
%           y_B:    Y-Position of Point B in m

%Outputs:   F_AB_x:   Force in X-Direction Acting on Body B generated by Body A in N
%           F_AB_y:   Force in Y-Direction Acting on Body B generated by Body A in N

%% Constants
G = 6.674e-11;   % Gravitational Consant in N(m/kg)²

%% Calculation
d_AB = distance(x_A, x_B, y_A, y_B);         % Distance Between Point A and B in m
F_AB_x = (G*m_A*m_B*(x_A-x_B))/(d_AB^3);    % Force in X- Direction Acting on Body B generated by Body A in N
F_AB_y = (G*m_A*m_B*(y_A-y_B))/(d_AB^3);    % Force in Y- Direction Acting on Body B generated by Body A in N
end